# GOPI configuration file
pkgInfoFile: pkg.info
iconPath: __resources/images/icon100.png
readmeFile: README.md
archList:
    - linux_amd64
    - linux_arm64
    - darwin_amd64
    - darwin_arm64
    - windows
